### ISSUE TITLE
MAINTENANCE - Org list

### ISSUE THREAD

**Issue by Jackseed** [blockframes/blockframes#2803]

**Comment by maltmayer** [comment]
- [ ] page should only show sales agents, not all orgs
![image](https://user-images.githubusercontent.com/55785823/82904469-cf321a00-9f62-11ea-89da-cd2f971774d9.png)

**Comment by ioaNikas** [comment]
> * [ ]  page should only show sales agents, not all orgs
>   ![image](https://user-images.githubusercontent.com/55785823/82904469-cf321a00-9f62-11ea-89da-cd2f971774d9.png)

Good point on this one. The query is incomplete, Archipel Market appears because it have access to everything :). We will exclude it as it is a very specific case.

**Comment by maltmayer** [comment]
- [ ] Also, same problem as Clélia sorted on org view. Country should have capital letter. Here it shows "france" instead of "France"

**Comment by maltmayer** [comment]
- [ ] logos should be round
![image](https://user-images.githubusercontent.com/55785823/83049266-30351d00-a04b-11ea-8b2d-b916634896f2.png)

**Comment by Mussuranae** [comment]
The problem of the capitalized letter of country should be corrected now.

**Comment by maltmayer** [comment]
- [ ] Still have the display problem with countries when address is not 100% complete
![image](https://user-images.githubusercontent.com/55785823/83264534-824b7f00-a1c0-11ea-9c3e-6d5cffe074ce.png)
