### ISSUE TITLE
Licence End Date input field clips outside of avails filter

### ISSUE THREAD

**Issue by frenchyrules** [blockframes/blockframes#6628]
**Film page**

- [ ] wrap input field underneath license start date input
![image.png](https://images.zenhubusercontent.com/611a265d2ea95c7880c91192/bf47a20e-993c-4ce8-a141-5388974dede7)

**Comment by iPR0D1G1** [comment]
<img width="1440" alt="Bildschirmfoto 2021-11-04 um 12 37 57 PM" src="https://user-images.githubusercontent.com/22674720/140307168-c1a2ef3c-ca72-4f78-8881-064c1a7118bd.png">
I just verified and the problem has been resolved.

**Comment by stephanie-cascade8** [comment]
@yspringfield @RemcoSimonides the problem is still there. You have to be on mobile sizes to see it. 
Here is a screenshot (from my computer ->
<img width="495" alt="Capture d’écran 2021-11-04 à 13 35 32" src="https://user-images.githubusercontent.com/66258851/140314518-220a2d33-7c06-4ec7-b919-47c82c9a2093.png">
 mobile size in the navigator)

**Comment by cams-goussale** [comment]
Hey! I'd suggest @RemcoSimonides that we
- move this issue to sanity
- with medium priority
- treat the issue whenever this one is also ready for dev #6627

This way, the dev who'll be working on this will do everything at once.

**Comment by cams-goussale** [comment]
Let's keep 1 issue for filters on mobile #6629
